import "../styles/globals.css";
import { initializeApp } from "firebase/app";
import { initializeAuth } from "firebase/auth";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firebaseConfig = {
  apiKey: process.env.NEXT_APP_API_KEY,
  authDomain: "tech-tide-to-do.firebaseapp.com",
  databaseURL: "https://tech-tide-to-do-default-rtdb.firebaseio.com",
  projectId: "tech-tide-to-do",
  storageBucket: "tech-tide-to-do.appspot.com",
  messagingSenderId: "778868147570",
  appId: "1:778868147570:web:bcef5b1aaa5f27e1b589eb",
};

const app = initializeApp(firebaseConfig);
const auth = initializeAuth(app);
auth.settings.appVerificationDisabledForTesting = true;

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <script src='../script/firebase.js'></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
